- name : Generate service_app file using jinja2
  ansible.builtin.template:
    src : service_app.j2
    dest: "/etc/systemd/system/{{ app_name }}.service"
  register: template_output
  notify:
    - Reload systemd daemon


- name: Debug output of creating .service file
  ansible.builtin.debug:
    msg: template_output

- name: Restart the service
  ansible.builtin.service:
    name: "{{ app_name }}"
    state: restarted
    enabled: yes