- name : Generate service_app file using jinja2
  ansible.builtin.template:
    src : service_app.j2
    dest: "/etc/systemd/system/{{ app_name }}.service"
  register: template_output
  notify:
    - Reload systemd daemon
    - Enable and start the service


- name: Debug output of creating .service file
  ansible.builtin.debug:
    msg: template_output