- name: Print the working Dir
  ansible.builtin.debug:
    msg: source file 🫸 {{ src_jar_file }}/{{ app_name }}.jar

- name: Print the working Dir
  ansible.builtin.debug:
    msg: dest file 🫸 {{ working_dir }}/{{ app_name }}.jar


- name: Copy the Uber JAR file
  copy:
    src: "{{ src_jar_file }}/{{ app_name }}.jar"
    dest: "{{ working_dir }}/{{ app_name }}.jar"
    group: sudo
    mode: '0755'


- name : Generate maven-package.sh file using jinja2
  ansible.builtin.template:
    src : service_app.j2
    dest: "/etc/systemd/system/{{ app_name }}.service"
  register: template_output
  notify:
    - Reload systemd daemon
    - Enable and start the service


- name: Debug output of creating .service file
  ansible.builtin.debug:
    msg: template_output