- name: Ensure Nginx directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    group: sudo
  with_items:
    - "{{ working_dir }}"


- name: Print the working Dir
  ansible.builtin.debug:
    msg: {{ working_dir }}


- name: Git checkout
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: "{{ working_dir }}"