- name: Install Java-17 And Maven packages on Debian/Ubuntu
  ansible.builtin.apt:
    name:
      - openjdk-17-jdk-headless
      - maven
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"


- name: Install Java-17 And Maven packages on Red Hat/CentOS
  ansible.builtin.yum:
    name:
      - java-17-openjdk-devel
      - maven
    state: present
  when: ansible_os_family == "RedHat"


- name: Set JAVA_HOME in /etc/environment
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'
    state: present

- name: Set MAVEN_HOME in /etc/environment
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: 'MAVEN_HOME=/usr/share/maven'
    state: present

- name: Update PATH in /etc/environment
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: 'PATH=$PATH:$JAVA_HOME/bin:$MAVEN_HOME/bin'
    state: present

- name: Reload environment variables
  ansible.builtin.shell: source /etc/environment
  args:
    executable: /bin/bash
