- name: Install Java-17 And Maven packages on Debian/Ubuntu
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - openjdk-17-jdk-headless
      - maven
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"


- name: Install Java-17 And Maven packages on Red Hat/CentOS
  ansible.builtin.yum:
    name:
      - python3
      - python3-pip
      - java-17-openjdk-devel
      - maven
    state: present
  when: ansible_os_family == "RedHat"



- name: Install required Python libraries for AWS (boto3, botocore)
  ansible.builtin.pip:
    name:
      - boto3
      - botocore
    state: present
    executable: python3