---
# tasks file for java_app

- name: Checkout A Java (Mvn) App Using Git Then Package It.
  block:
    - ansible.builtin.include_tasks: install_dependencies.yml
    - ansible.builtin.include_tasks: create_working_dirs.yml
    - ansible.builtin.include_tasks: download_jar_file.yml
    - ansible.builtin.include_tasks: deploy.yml
    # - ansible.builtin.include_tasks: package_app.yml