- name: Debug environment variables
  ansible.builtin.shell: env
  register: env_output

- name: Print environment variables
  ansible.builtin.debug:
    var: env_output.stdout


# - name: Print the working Dir
#   ansible.builtin.debug:
#     msg: dpkg_dir 🔖 {{ dpkg_dir }}



- name: Running mvn package
  shell: "mvn package"
  register: mvn_result
  args:
    chdir: "{{ dpkg_dir }}"

- name: "mvn clean task output"
  debug:
    var: mvn_result