- name: Debug environment variables
  ansible.builtin.shell: env
  register: env_output

- name: Print environment variables
  ansible.builtin.debug:
    var: env_output.stdout


# - name: Print the working Dir
#   ansible.builtin.debug:
#     msg: dpkg_dir 🔖 {{ dpkg_dir }}


- name : Generate maven-package.sh file using jinja2
  ansible.builtin.template:
    src : shell.j2
    dest: "{{ dpkg_dir }}/maven-package.sh"

- name: Set permissions on maven-package.sh
  ansible.builtin.file:
    path: "{{ dpkg_dir }}/maven-package.sh"
    mode: '0755'

- name: Run Maven clean and package script
  ansible.builtin.shell:
    cmd: "{{ dpkg_dir }}/maven-package.sh"