- name: Generate SSL certificate
  ansible.builtin.command:
    cmd: >
      certbot --nginx
      --non-interactive
      --agree-tos
      --email "{{ acme_account_email }}"
      --domains "{{ service_host_name }}"
  register: certbot_output
  ignore_errors: yes

- name: Debug Certbot output
  ansible.builtin.debug:
    var: certbot_output

- name: Fail if Certbot failed
  ansible.builtin.fail:
    msg: "Certbot failed to generate the SSL certificate. Check the logs for more details."
  when: certbot_output.rc != 0