- name: Install Certbot packages on Debian/Ubuntu
  ansible.builtin.apt:
    name:
      - certbot
      - certbot-nginx
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags:
    - nginx
    - certbot


- name: Install Certbot packages on Red Hat/CentOS
  ansible.builtin.yum:
    name:
      - certbot
      - certbot-nginx
    state: present
  when: ansible_os_family == "RedHat"


- name: Verify Certbot installation
  ansible.builtin.command:
    cmd: certbot --version
  register: certbot_version
  changed_when: false

- name: Debug Certbot version
  ansible.builtin.debug:
    var: certbot_version.stdout



# register the certbot

- name: Register certbot
  shell: |
    certbot -n register --agree-tos --email "{{ acme_account_email }}"
    touch /etc/letsencrypt/.registered
  args:
    creates: /etc/letsencrypt/.registered
  tags:
    - nginx
    - certbot